title: Photocreep
description: A movie with line yet to be written
baseurl: "/photocreep"
url: "https://konstantinbarkalov.github.io"
version: "0.0.0.azzb"
last_updated: 2025-06-23

# Build settings
markdown: kramdown

# Multilingual settings
languages:
  - code: en
    name: English
    default: true
  - code: ru
    name: Русский
  - code: th
    name: ไทย

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "en"
    values:
      lang: "en"
      lang_name: "EN"
  - scope:
      path: "ru"
    values:
      lang: "ru"
      lang_name: "RU"
  - scope:
      path: "th"
    values:
      lang: "th"
      lang_name: "TH"
